name: create_release_minor_
# release verison is patch v0.1.0

on:
  pull_request:
    types: [closed]

jobs:
  create_release_minor:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'create release minor') && github.event.pull_request.user.login == 'jge162'
    steps:
      - name: Python Action
        uses: jge162/Action-workflows@2.1.1

      - name: Get latest tag
        run: |
          git fetch --tags
          echo "::set-output name=latest_tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
        id: get_latest_tag

      - name: Bump minor version
        run: |
          semver=$(echo "${{ steps.get_latest_tag.outputs.latest_tag }}")
          major=$(echo $semver | cut -d'.' -f1)
          minor=$(echo $semver | cut -d'.' -f2)
          patch=$(echo $semver | cut -d'.' -f3)
          new_minor=$((minor+1))
          new_tag="$major.$new_minor.$patch"
          echo "::set-output name=new_tag::$new_tag"
        id: bump_version

      - name: create-release-on-close
        uses: jge162/create-release@2.2.1
        with:
          files: |
            build/*
          #tag_name: ${{ env.latest_tag }}
          #prerelease: Release ${{ env.new_tag }}
          #body: This is a new release ${{ env.new_tag }} which will include bug fixes and minor updates.            
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          prerelease: Release ${{ steps.bump_version.outputs.new_tag }}
          body: This is a new release ${{ steps.bump_version.outputs.new_tag }} which will include bug fixes and minor updates.
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
 


  ChangeLog_Enforcer:
    runs-on: ubuntu-latest
    needs: [create_release_minor]

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get latest version
        id: get_latest_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          latest_version=${latest_tag#v}
          echo "::set-output name=latest_version::$latest_version"
        shell: bash

      - name: Get pull request number
        id: get_pull_request_number
        run: echo "::set-output name=pull_request_number::${{ github.event.number }}"

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          latest-version: ${{ steps.get_latest_version.outputs.latest_version }}
          release-notes: |
            Pull request number for the release is: [#${{ steps.get_pull_request_number.outputs.pull_request_number }}](${{ github.event.pull_request.html_url }})
      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
